// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8x1as1FOdv-Qk7aYIh2ootKAvEBJkGWo',
    appId: '1:635396701378:web:1e78c712f95061458c4f5b',
    messagingSenderId: '635396701378',
    projectId: 'reminder-app-eslam-2026',
    authDomain: 'reminder-app-eslam-2026.firebaseapp.com',
    storageBucket: 'reminder-app-eslam-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXcHnWbtElfqO4p33YwvIEzq-d455dWw',
    appId: '1:635396701378:android:9c0363cc94069fc98c4f5b',
    messagingSenderId: '635396701378',
    projectId: 'reminder-app-eslam-2026',
    storageBucket: 'reminder-app-eslam-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClj2lotDzNHAuiM0qoe-TCeTv8sLob7so',
    appId: '1:635396701378:ios:760febdd8a0b27298c4f5b',
    messagingSenderId: '635396701378',
    projectId: 'reminder-app-eslam-2026',
    storageBucket: 'reminder-app-eslam-2026.firebasestorage.app',
    iosBundleId: 'com.reminder.en',
  );
}
